# Generated by Django 4.2.6 on 2023-11-22 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedUnit',
            fields=[
                ('id', models.CharField(editable=False, max_length=30, primary_key=True, serialize=False, unique=True)),
                ('students_course', models.CharField(max_length=50)),
                ('course_name', models.CharField(max_length=80)),
                ('year_of_study', models.CharField(max_length=10)),
                ('semester', models.CharField(max_length=1)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.faculty')),
            ],
            options={
                'verbose_name_plural': 'Booked units',
                'ordering': ['lecturer', 'course_name'],
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.CharField(editable=False, max_length=30, primary_key=True, serialize=False, unique=True)),
                ('lecture_date', models.DateField()),
                ('start_time', models.TimeField(db_column='Scheduled start time')),
                ('end_time', models.TimeField(db_column='Scheduled end time')),
                ('recurrence_pattern', models.CharField(max_length=10)),
                ('total_students', models.PositiveIntegerField(default=0, editable=False)),
                ('is_attending', models.BooleanField(default=False)),
                ('is_taught', models.BooleanField(default=False, editable=False)),
                ('date_scheduled', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Scheduled lectures',
                'ordering': ['lecturer', 'lecture_hall', '-date_scheduled'],
            },
        ),
        migrations.CreateModel(
            name='LectureHall',
            fields=[
                ('id', models.CharField(editable=False, max_length=30, primary_key=True, serialize=False, unique=True)),
                ('academic_block', models.CharField(max_length=20)),
                ('hall_no', models.CharField(max_length=5, unique=True)),
                ('seating_capacity', models.PositiveIntegerField(default=0)),
                ('floor', models.CharField(max_length=7)),
                ('rating', models.PositiveIntegerField(default=0, editable=False)),
                ('image', models.ImageField(default='lecture-hall.png', upload_to='Lecture-Halls/img/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Lecture halls',
                'ordering': ['academic_block', 'hall_no'],
            },
        ),
        migrations.CreateModel(
            name='RegisteredUnit',
            fields=[
                ('id', models.CharField(editable=False, max_length=30, primary_key=True, serialize=False, unique=True)),
                ('is_registered', models.BooleanField(default=False, editable=False)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.bookedunit')),
            ],
            options={
                'verbose_name_plural': 'Registered units',
                'ordering': ['student', 'unit'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.CharField(editable=False, max_length=30, primary_key=True, serialize=False, unique=True)),
                ('message', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('scheduled_lecture', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='campus.lecture')),
            ],
            options={
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date_created', 'message'],
            },
        ),
        migrations.AddField(
            model_name='lecture',
            name='lecture_hall',
            field=models.ForeignKey(db_column='Venue', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='campus.lecturehall'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='lecturer',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='accounts.faculty'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='student',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.student'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='unit_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.bookedunit'),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.CharField(editable=False, max_length=30, primary_key=True, serialize=False, unique=True)),
                ('complaint', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('rate_score', models.PositiveIntegerField(default=0)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('lecture_hall', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='campus.lecturehall')),
                ('student', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
            options={
                'verbose_name_plural': 'Feedback',
                'ordering': ['lecture_hall', '-date_posted'],
            },
        ),
    ]
